version: 1
debug: false
# Random number from min_chop_amount to max_chop_amount.
min_chop_amount: 5
max_chop_amount: 10
player_chop_regions: # Название регионов, где игрок сможет рубить деревья
  - forest
  - forest2
tree_regenerate_time: 30000 # Через сколько миллисекунд регенерировать срубленное дерево.
lvl: # Если не указать некоторое значение, то будет брать с default_player_data
  1: # Начинаем с первого уровня, нулевой уровень находится в default_player_data
    award: 100 # Премия
    money_per_tree: 1.0 # Цена за каждое дерево при продаже
    max_tree: 10 # Максимум дерева, которое можно срубить за один заход. (Виртуальное хранилище)
    per_tree_award: 16 # Каждые сколько срубленных деревьев выдавать премию
    per_item_sell_limit: 64 # Лимит продажи для всех предметов
    per_wood_exp: 0.2 # Опыт за каждое срубленное бревно
    next_lvl_exp: 5.0 # Опыт для следующего уровня
# Некоторые данные из списка собираются прямо в игре, они не обнуляются после достижения нового уровня.
default_player_data:
  award: 10 # Премия
  current_wood: 0 # Количество бревна, которое нужно срубить, чтобы упало дерево (Не трогать)
  total_wood: 0 # Общее количество срубленного бревна
  money_per_tree: 1.0 # Цена за каждое дерево при продаже
  current_tree: 0 # Текущее количество срубленных деревьев (После продажи сбрасывается)
  max_tree: 10 # Максимум дерева, которое можно срубить за один заход. (Виртуальное хранилище)
  total_tree: 0 # Общее количество срубленного дерева
  per_tree_award: 16 # Каждые сколько срубленных деревьев выдавать премию
  per_item_sell_limit: 0 # Лимит продажи для всех предметов
  lvl: 0 # Уровень игрока
  current_exp: 0.0 # Текущий опыт
  per_wood_exp: 0.1 # Опыт за каждое срубленное бревно
  next_lvl_exp: 1.0 # Опыт для следующего уровня
  total_exp: 0.0 # Общее количество опыта
  local_booster_time: 0 # Время локального бустера